product = [
    "Shop có bán quần short không?",
    "Áo thun nam giá bao nhiêu vậy?",
    "Có đồ cho bé gái 3 tuổi không?",
    "Shop có nhận giao hàng không? Phí ship là bao nhiêu?",
    "Mũ len bên shop giá khoảng bao nhiêu?",
    "Áo sơ mi nữ size M còn không?",
    "Shop có bán quần legging không? Giá rẻ nhất là bao nhiêu?",
    "Quần áo của shop có phù hợp với người cao 1m60 không?",
    "Có chương trình khuyến mãi nào cho sinh viên không?",
    "Tôi muốn mua một chiếc áo khoác, mẫu nào đang được nhiều người chọn?",
    "Shop có bán áo phông không?",
    "Tôi cần tìm một đôi giày trắng, có mẫu nào không?",
    "Có đồ cho trẻ em không?",
    "Quần jeans nam giá khoảng bao nhiêu?",
    "Shop có mở cửa vào cuối tuần không?",
    "Tôi muốn mua một chiếc túi xách cho nữ, có mẫu nào không?",
    "Có chương trình khuyến mãi nào đang diễn ra không?",
    "Áo sơ mi nữ bên shop giá như thế nào?",
    "Shop có mẫu giày thể thao nào màu trắng, giá dưới 1 triệu không?",
    "Tôi cần mua một bộ đồ đi làm phù hợp với thời tiết nóng, có gợi ý nào không?",
    "Có mẫu áo dài cách tân nào trẻ trung không?",
    "Shop có thể gợi ý quần áo phù hợp cho người dáng gầy không?",
    "Tôi muốn mua đồ đôi cho cặp vợ chồng, có mẫu nào dễ thương không?",
    "Tôi cần một bộ đồ ngủ bằng lụa, có màu xanh không?",
    "Có mẫu nào phù hợp để mặc đi picnic ngoài trời không?",
    "Tôi muốn mua áo thun in hình, shop có hỗ trợ thiết kế theo ý tôi không?",
    "Áo vest nữ bên shop có size lớn không? Tôi cần size XXL.",
    "Có giày boot nào phù hợp để đi dưới mưa mà vẫn thời trang không?",
    "Sắp tới sinh nhật vợ tôi rồi, hãy gợi ý cho tôi vài món giá dưới 500k, cô ấy thích màu đỏ.",
    "Tôi đang tìm quần áo thể thao, shop có không?",
    "Dạo này tôi không thích mặc váy nữa, gợi ý cho tôi vài món khác váy đi.",
    "Có sản phẩm nào mới về trong tuần này không?",
    "Tôi cao 1m70, nặng 65kg, có áo khoác nào phù hợp không?",
    "Tôi cần mua một đôi giày cao gót dưới 7cm, có mẫu nào không?",
    "Tôi muốn mua quần áo cho bé trai 5 tuổi, shop có không?",
    "Có bộ đồ nào phù hợp cho người đi làm văn phòng không?",
    "Shop có bán phụ kiện thời trang như kính mắt hay mũ không?",
    "Tôi chuẩn bị đi du lịch châu Âu vào cuối năm, shop có thể gợi ý một set đồ ấm áp không?",
    "Tôi muốn tặng quà cho mẹ, khoảng 500k, mẹ tôi thích phong cách thanh lịch. Có gợi ý nào không?",
    "Có quần áo nào phù hợp với người đang mang bầu mà vẫn thời trang không?",
    "Tôi muốn phối một set đồ đen toàn bộ nhưng không muốn trông nhàm chán, shop có thể tư vấn không?",
    "Shop có bán váy maxi không? Tôi cao 1m50, liệu mặc có phù hợp không?",
    "Shop có sản phẩm nào từ chất liệu thân thiện với môi trường không? Tôi muốn mua để bảo vệ môi trường.",
    "Có mẫu quần nào phù hợp cho người béo bụng nhưng vẫn năng động không?",
    "Tôi muốn đặt đồ nhóm cho công ty (khoảng 20 người), cần đồng phục lịch sự nhưng thoải mái. Có mẫu nào phù hợp không?",
    "Tôi chuẩn bị dự một buổi tiệc ngoài trời, phong cách sang trọng nhưng không quá cầu kỳ. Gợi ý giúp tôi vài mẫu nhé.",
    "Tôi muốn đặt thiết kế riêng một bộ đồ theo kiểu truyền thống kết hợp hiện đại, liệu shop có nhận không?",
    "Tôi muốn đổi chiếc áo đã mua vì không vừa, shop có chính sách đổi trả không?",
    "Tôi muốn đặt đồ online, nhưng shop có giao hàng toàn quốc không?",
    "Làm thế nào để biết size đồ nào phù hợp với tôi?",
    "Áo len mà shop bán có bị xù lông sau vài lần giặt không?",
    "Shop có quần áo nào làm từ vải thân thiện với môi trường không?",
    "Tôi muốn mua đồ đôi cho cặp đôi, gợi ý giúp tôi vài bộ.",
    "Có mẫu quần nào phù hợp cho người đùi to nhưng vẫn thoải mái không?",
    "Shop có thiết kế riêng theo yêu cầu không? Tôi muốn làm một chiếc áo đặc biệt.",
    "Tôi ở Đà Nẵng, phí vận chuyển cho đơn hàng dưới 1 triệu là bao nhiêu?",
    "Chiếc áo này có những màu nào vậy?",
    "Size L của quần này có vừa với người cao 1m70 không?",
    "Chất liệu của chiếc váy này là gì?",
    "Giày này có chống nước không?",
    "Chiếc áo khoác này có giữ ấm tốt vào mùa đông không?",
    "Tôi nên phối chiếc quần này với áo màu gì thì đẹp?",
    "Sản phẩm này có được đổi trả không?",
    "Giày này có phù hợp để chạy bộ không?",
    "Chiếc túi này có ngăn đựng laptop không?",
    "Áo này có bị co rút sau khi giặt không?",
    "Váy này có form rộng hay ôm sát vậy?",
    "Quần jean này có co giãn không?",
    "Đây là hàng chính hãng hay hàng nhập khẩu?",
    "Tôi có thể xem thêm hình ảnh chi tiết của sản phẩm không?",
    "Chiếc áo này có kèm theo phụ kiện không?",
    "Sản phẩm này còn size XL không?",
    "Tôi có thể giặt chiếc áo này bằng máy giặt không?",
    "Giày này có bền không nếu sử dụng hằng ngày?",
    "Chính sách bảo hành của sản phẩm này như thế nào?",
    "Sản phẩm này phù hợp cho mùa hè hay mùa đông?",
    "Đôi giày này có bị trơn trượt khi đi mưa không?",
    "Quần này có túi không? Túi có sâu không?",
    "Chiếc váy này có dễ nhăn không?",
    "Áo này có phù hợp cho cả nam và nữ không?",
    "Sản phẩm này có phải là hàng mới 100% không?",
    "Có chương trình giảm giá nào cho sản phẩm này không?",
    "Tôi nên mang giày size nào nếu chân tôi dài 24cm?",
    "Chất liệu này có thấm hút mồ hôi không?",
    "Áo này có bị phai màu khi giặt không?",
    "Chiếc quần này có phù hợp để đi làm không?",
    "Chiếc túi này có nặng không?",
    "Áo khoác này có chống gió không?",
    "Sản phẩm này có thể mặc vào mùa thu được không?",
    "Chiếc mũ này có điều chỉnh được kích thước không?",
    "Quần short này có co giãn tốt không?",
    "Tôi có thể phối chiếc váy này với giày cao gót không?",
    "Sản phẩm này có phải là vải cotton 100% không?",
    "Tôi có thể xem bảng size chi tiết của sản phẩm không?",
    "Đôi giày này có phù hợp để đi chơi hay đi làm không?",
    "Sản phẩm này có giao hàng toàn quốc không?",
    "Áo này có bị xù lông sau khi mặc một thời gian không?",
    "Tôi cao 1m65, nặng 55kg thì nên chọn size nào?",
    "Chất liệu này có thoáng mát vào mùa hè không?",
    "Quần này có phù hợp cho người lớn tuổi không?",
    "Chiếc áo này có cổ cao hay cổ tròn?",
    "Sản phẩm này có kèm theo hướng dẫn giặt không?",
    "Tôi muốn mua số lượng lớn, có được giảm giá không?",
    "Chiếc váy này có lớp lót bên trong không?",
    "Giày này có đế cao bao nhiêu cm?",
    "Sản phẩm này có dễ bảo quản không?",
    "Túi này có khóa kéo không?",
    "Áo này có phù hợp với phong cách công sở không?",
    "Quần này có dễ bị phai màu không?",
    "Đôi giày này có bị nặng chân khi đi không?",
    "Sản phẩm này có màu sắc nào đang hot hiện nay?",
    "Tôi muốn đổi size, phải làm thế nào?",
    "Áo này có phải là hàng xuất khẩu không?",
    "Quần này có phù hợp cho người bụng to không?",
    "Chiếc túi này có thể đựng vừa sách vở không?",
    "Sản phẩm này có khuyến mãi gì trong tháng này không?",
    "Tôi có thể giặt sản phẩm này bằng nước ấm không?",
    "Giày này có gây đau chân khi đi lâu không?",
    "Áo này có mỏng quá không?",
    "Quần này có khóa kéo hay nút bấm vậy?",
    "Sản phẩm này có size cho trẻ em không?",
    "Chiếc váy này có cần ủi thường xuyên không?",
    "Chất liệu này có bị nóng vào mùa hè không?",
    "Đôi giày này có phù hợp cho người bị đau chân không?",
    "Áo này có bị chảy xệ sau khi giặt không?",
    "Sản phẩm này có sẵn hàng hay phải đặt trước?",
    "Chiếc túi này có chống nước không?",
    "Quần này có độ dài bao nhiêu cm?",
    "Áo khoác này có lót lông bên trong không?",
    "Tôi có thể đặt hàng qua website không?",
    "Chiếc váy này có phù hợp để đi tiệc không?",
    "Giày này có lót đệm bên trong không?",
    "Quần này có phù hợp để tập thể thao không?",
    "Sản phẩm này có phải là vải linen không?",
    "Áo này có cổ tay dài hay ngắn vậy?",
    "Chiếc túi này có ngăn đựng điện thoại không?",
    "Sản phẩm này có bảo hành bao lâu?",
    "Quần này có bị xù lông sau khi giặt không?",
    "Áo này có cần giặt khô không?",
    "Sản phẩm này có free ship không?",
    "Giày này có thể mang vào mùa đông không?",
    "Tôi muốn xem sản phẩm trực tiếp thì làm thế nào?",
    "Quần này có vừa với người nặng 70kg không?",
    "Chiếc áo này có họa tiết hay trơn màu?",
    "Túi này có quai đeo chéo không?",
    "Áo này có lớp lót bên trong không?",
    "Sản phẩm này có phù hợp cho dịp đặc biệt không?",
    "Chiếc váy này có form dài hay ngắn vậy?",
    "Quần này có túi sau không?",
    "Giày này có thể lau sạch bằng khăn ướt không?",
    "Áo này có dễ nhăn khi mặc không?",
    "Tôi nên bảo quản sản phẩm này như thế nào?",
    "Chiếc túi này có khóa bấm chắc chắn không?",
    "Sản phẩm này có phù hợp với mọi lứa tuổi không?",
    "Áo này có họa tiết in hay thêu?",
    "Tôi có thể xem video review sản phẩm không?",
    "cho tôi xem sản phẩm này đi"
    "Chiếc váy này có thắt lưng đi kèm không?",
    "Sản phẩm này có màu pastel không?",
    "Quần này có dễ rách không nếu sử dụng thường xuyên?",
    "Giày này có bám đường tốt không?",
    "Áo này có cổ bẻ hay cổ tròn vậy?",
    "Tôi muốn tặng quà sinh nhật cho bạn gái, nhưng không biết cô ấy thích gì, shop có thể giúp tôi chọn không?",
    "Tôi muốn tìm một set đồ mùa hè phù hợp với người da ngăm. Có cách phối đồ nào làm sáng da không?",
    "Áo khoác dáng dài thường làm tôi trông thấp hơn, shop có mẫu nào hoặc cách phối giúp trông cao hơn không?",
    "Tôi thích phong cách streetwear nhưng không muốn quá nổi bật. Shop có gợi ý sản phẩm và phụ kiện không?",
    "Tôi là giáo viên, cần một set đồ phù hợp để đi dạy học nhưng vẫn trẻ trung. Có mẫu nào không?",
    "Tôi vừa mua một chiếc váy từ shop nhưng không vừa. Nếu muốn đổi size, tôi cần làm gì?",
    "Tôi muốn tìm trang phục cho sự kiện công ty nhưng không thích đồ đơn sắc, có mẫu nào phối màu đẹp không?",
    "Nếu tôi muốn đặt hàng số lượng lớn (100 chiếc áo thun) để làm từ thiện, shop có giảm giá không?",
    "Tôi cần một bộ suit nữ phá cách, không quá cứng nhắc, có mẫu nào mới nhất không?",
    "Tôi thích thời trang tối giản nhưng muốn thêm điểm nhấn bằng phụ kiện, shop có thể gợi ý không?",
    "Shop có thể tư vấn giúp tôi cách bảo quản áo len để không bị giãn hay xù lông không?",
    "Shop có thể gợi ý trang phục phù hợp cho tiệc cưới ban ngày không? Tôi muốn mặc màu pastel.",
    "Tôi muốn mua một chiếc áo sơ mi không nhăn và dễ giặt, có mẫu nào không?",
    "vậy còn cái thứ hai thì sao",
    "sản phẩm mới",
    "đầm đen",
    "quần áo váy",
    "cho tôi thông tin chi tiết của cái đầu tiên"
    "Tôi là người theo phong cách minimal, gợi ý cho tôi vài sản phẩm thời trang phù hợp với phong cách này.",
    "Tôi muốn phối một bộ đồ vừa thoải mái vừa lịch sự để đi phỏng vấn xin việc. Tôi cao 1m75, da ngăm, phong cách của tôi khá tối giản. Có gợi ý nào không?",
]
chitchat = [
    "Hôm nay thời tiết thế nào?",
    "Mọi thứ thế nào rồi?",
    "Kể cho tôi một câu chuyện cười.",
    "Bạn có khỏe không?",
    "Hãy đi ăn khoai tây chiên.",
    "Bạn đang làm gì vậy?",
    "Có gì mới không?",
    "Hôm nay bạn thấy vui không?",
    "Bạn có thích uống cà phê không?",
    "Hãy kể cho tôi một câu chuyện thú vị.",
    "Bạn có thích đi du lịch không?",
    "Hôm nay bạn ăn gì rồi?",
    "Trời mưa thế này bạn có thấy buồn không?",
    "Hãy nói một câu gì đó vui vẻ.",
    "Bạn thích nghe nhạc thể loại gì?",
    "Có bộ phim nào bạn muốn xem không?",
    "Hãy gợi ý cho tôi một bài hát hay.",
    "Bạn thích đọc sách chứ?",
    "Kể một bí mật nhỏ của bạn đi.",
    "Bạn có thích mèo hay chó hơn?",
    "Hôm nay có gì đặc biệt không?",
    "Cuối tuần này bạn có kế hoạch gì chưa?",
    "Nếu có thể đi đâu đó ngay bây giờ, bạn sẽ đi đâu?",
    "Bạn có thích ăn kem không?",
    "Hãy kể một kỷ niệm đáng nhớ của bạn.",
    "Bạn thấy tôi thế nào?",
    "Hãy chia sẻ một câu danh ngôn hay.",
    "Hôm nay bạn mặc gì vậy?",
    "Bạn có tin vào may mắn không?",
    "Hãy nói một điều khiến bạn vui vẻ hôm nay.",
    "Nếu được chọn một siêu năng lực, bạn sẽ chọn gì?",
    "Bạn thích mùa nào nhất?",
    "Kể một câu chuyện hài hước đi nào.",
    "Bạn có thích đi biển không?",
    "Hãy kể cho tôi một điều thú vị về bạn.",
    "Bạn đã bao giờ thử nấu ăn chưa?",
    "Hôm nay bạn có thấy mệt không?",
    "Nếu có thể thay đổi một điều gì đó, bạn sẽ thay đổi gì?",
    "Bạn thích màu sắc nào nhất?",
    "Bạn nghĩ gì về tình yêu?",
    "Hãy kể một câu chuyện ngày xưa của bạn.",
    "Bạn có thích chơi thể thao không?",
    "Hôm nay bạn học được điều gì mới?",
    "Bạn có tin vào số phận không?",
    "Hãy kể về một ngày hoàn hảo của bạn.",
    "Nếu được đi ăn tối với ai đó nổi tiếng, bạn sẽ chọn ai?",
    "Bạn có thích ngày mưa không?",
    "Hãy kể một câu chuyện ngắn về tình bạn.",
    "Bạn thích ăn bánh gì nhất?",
    "Nếu được chọn một nơi để sống, bạn sẽ chọn ở đâu?",
    "Bạn có thích hát karaoke không?",
    "Hãy kể về một bộ phim bạn yêu thích.",
    "Bạn đã từng thử làm điều gì điên rồ chưa?",
    "Bạn thích ngủ nướng không?",
    "Nếu bạn trúng số, bạn sẽ làm gì đầu tiên?",
    "Bạn có thích đi bộ vào buổi sáng không?",
    "Hãy kể về một món ăn bạn thích nhất.",
    "Bạn thích làm gì vào thời gian rảnh?",
    "Nếu bạn có thể quay ngược thời gian, bạn sẽ làm gì?",
    "Bạn đã bao giờ gặp một người nổi tiếng chưa?",
    "Hãy nói một điều bạn đang mong chờ.",
    "Bạn có thích đi xem hòa nhạc không?",
    "Nếu bạn có thể học một kỹ năng mới, bạn sẽ chọn gì?",
    "Bạn đã bao giờ thử chơi một nhạc cụ chưa?",
    "Bạn có thích ăn đồ ngọt không?",
    "Nếu được đi dã ngoại, bạn sẽ mang gì theo?",
    "Hãy kể về một người bạn đặc biệt của bạn.",
    "Bạn có tin vào phép màu không?",
    "Nếu bạn có một ngày nghỉ, bạn sẽ làm gì?",
    "Bạn thích xem phim ở nhà hay ra rạp hơn?",
    "Hãy kể về một chuyến đi bạn từng trải qua.",
    "Bạn có thích ăn đồ ăn cay không?",
    "Hãy nói một điều bạn cảm thấy biết ơn hôm nay.",
    "Bạn thích mùa đông hay mùa hè hơn?",
    "Bạn có thích nghe podcast không?",
    "Hãy kể về một thói quen hằng ngày của bạn.",
    "Bạn đã từng thử làm bánh chưa?",
    "Bạn thích uống trà hay cà phê hơn?",
    "Nếu bạn có thể gặp lại một người trong quá khứ, bạn sẽ chọn ai?",
    "Bạn có thích xem phim hoạt hình không?",
    "Hãy kể về một món quà bạn từng nhận được.",
    "Bạn có thích tham gia các buổi tiệc không?",
    "Nếu bạn có thể đi du lịch vòng quanh thế giới, bạn sẽ đến đâu trước tiên?",
    "Bạn thích ngày Tết không?",
    "Hãy kể một câu chuyện kỳ lạ bạn từng nghe.",
    "Bạn có thích làm việc nhóm không?",
    "Nếu bạn mở một quán ăn, bạn sẽ bán món gì?",
    "Bạn có thích nghe kể chuyện không?",
    "Nếu bạn có thể thay đổi tên của mình, bạn sẽ chọn tên gì?",
    "Bạn thích ở thành phố hay nông thôn hơn?",
    "Hãy kể về một người truyền cảm hứng cho bạn.",
    "Bạn có thích chơi game không?",
    "Nếu bạn có một chiếc máy thời gian, bạn sẽ đi đến tương lai hay quá khứ?",
    "Bạn thích ăn gì vào buổi sáng?",
    "Hãy kể về một lần bạn thấy tự hào về bản thân.",
    "Bạn có thích xem các chương trình hài không?",
    "Bạn thích đi chơi vào ban ngày hay ban đêm hơn?",
    "Hãy nói về một kỷ niệm tuổi thơ của bạn.",
    "Bạn có thích đi xem pháo hoa không?",
    "Nếu bạn có thể nuôi một con vật lạ, bạn sẽ chọn gì?",
    "Bạn thích đi dạo công viên không?",
    "Hãy kể về một người bạn đã lâu không gặp.",
    "Bạn có thích tham gia các hoạt động tình nguyện không?",
    "Nếu bạn viết một cuốn sách, nó sẽ nói về điều gì?",
    "Bạn thích đi leo núi hay đi biển hơn?",
    "Hãy nói một điều khiến bạn hạnh phúc gần đây.",
    "Bạn có thích đi ngủ sớm không?",
    "Nếu bạn có thể sống ở một thời đại khác, bạn sẽ chọn thời đại nào?",
    "Hãy kể về một món ăn lạ bạn từng thử.",
    "Bạn có thích chơi cờ không?",
    "Nếu bạn là một siêu anh hùng, bạn sẽ có sức mạnh gì?",
    "Bạn có thích làm vườn không?",
    "Hãy nói một câu khiến bạn cảm thấy vui vẻ.",
    "Bạn thích nghe nhạc lúc làm việc không?",
    "Hãy kể về một ngày bạn thấy thật đặc biệt.",
]
